spring:
  application:
    # 应用名称
    name: adaptation
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: url
    username: username
    password: password
    dbcp2:
      default-query-timeout: 5
      initial-size: 1
      max-total: 10
  http:
    multipart:
      max-file-size: 2000MB
      max-request-size: 2000MB

server:
  # 端口
  port: 10080
#  context-path: /adaptation

mybatis:
  mapper-locations: classpath*:mybatis/*.xml
  type-aliases-package: com.jaiaxn.adaptation

logging:
  level:
    com:
      jaiaxn: DEBUG
