spring:
  application:
    # 应用名称
    name: adaptation
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: url
    username: username
    password: password
    dbcp2:
      default-query-timeout: 5
      initial-size: 1
      max-total: 10
  http:
    multipart:
      max-file-size: 2000MB
      max-request-size: 2000MB

server:
  # 端口
  port: 10080
#  context-path: /adaptation

mybatis:
  mapper-locations: classpath*:mybatis/*.xml
  type-aliases-package: com.jaiaxn.adaptation

logging:
  level:
    com:
      jaiaxn: DEBUG

demo:
  client:
    url: http://127.0.0.1:8080/
    username: demo
    password: demo
    skipVerify: true

xxl:
  job:
    enabled: false
    admin:
      addresses: http://localhost:9086/xxl-job-admin
    ### xxl-job, access token ### xxl-job, access token
    accessToken:
    executor:
      #每个执行器集群的唯一标示
      appname: executor-adaption
      ### xxl-job executor address
      ip:
      port: 8954
      logpath: ./logs/xxl-job
      ### xxl-job log retention days
      logretentiondays: -1
